if name='ACCESS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ADAM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ADDRESS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ADVANC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='AMERICAN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ANDI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ANSWER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='APPLIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='APPRECI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ARAB' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='AREA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ARGIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ARMENIA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ARMENIAN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ATTACK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='AUDIO' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BANK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BASE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BATTERI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BILL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BOOK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BRAIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BRIAN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BUILD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='BUTTON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CALIFORNIA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CALL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CAN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CARD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CASE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CENTER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CHANG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CHIP' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CIRCUIT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CLIENT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CODE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COLOR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COMMUN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COMP' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COMPANI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COMPIL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COMPUT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CONNECT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CONTROL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='COPI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CORRECT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CREAT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='CURRENT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DAI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DATA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DAVID' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DEPART' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DEPT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DESIGN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DETECTOR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DEVIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DISEAS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DISPLAI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DISTRIBUT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DOCTOR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DOESN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DRAW' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DRIVE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='DRUG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='EDU' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='EFFECT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ELECTR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ELECTRON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='EMAIL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ENGIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ERROR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='EVENT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='EXPERI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FACT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FAX' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FEEL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FILE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FIND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FOLLOWUP' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FONT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FOOD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FRI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FRIEND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='FUNCTION' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GEB' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GENER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GEORGIA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GIVE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GOOD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GORDON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GOVERN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GRAPHIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GREAT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GREEK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GROUND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='GROUP' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='HAPPEN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='HEAR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='HIGH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='HOME' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='IMAG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INCLUD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INFO' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INFORM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INPUT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INSTITUT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INTEREST' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='INTERNET' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ISRA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ISRAEL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='JEW' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='JEWISH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='JOHN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='KEYBOARD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='KEYWORD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='KILL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='KIND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='LEVEL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='LIST' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='LIVE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='LONG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MACHIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MAIL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MANAG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MARK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MED' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MEDIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MEDICIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MEMORI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MICHAEL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MIKE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MOTIF' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='MOTOROLA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NATION' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NETWORK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NEW' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NEWS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NEWSREAD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NOIS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='NUMBER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='OPER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='OPINION' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ORIGIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='OUTPUT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PAIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PALESTINIAN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PART' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PATIENT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PERSON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PHONE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PITT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PITTSBURGH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PLACE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='POINT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='POLICI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='POSIT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='POST' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='POWER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PROBLEM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PRODUCT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PROGRAM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PROJECT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='PUBLIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='QUESTION' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RADAR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RADIO' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='READ' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='REASON' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RECEIV' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='REMEMB' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='REPLI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='REPORT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='REQUIR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RESEARCH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RESPONS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='ROBERT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='RUN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SAT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SCHOOL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SCI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SCIENC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SCREEN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SELL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SEND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SERDAR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SERVER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SERVIC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SHOW' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SIDE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SIGNAL' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SOFTWAR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SOUND' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SOURC' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='STANDARD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='START' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='STATE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='STEVE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='STUDI' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SUBSCRIB' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SUGGEST' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SUN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SUPPORT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SWITCH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='SYSTEM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TALK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TECHNOLOG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TERMIN' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TEST' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='THAT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='THU' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TIME' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TREATMENT' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TRUE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TUE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TURKISH' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='TYPE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='UNIV' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='UNIVERS' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='UNIX' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='USENET' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='USER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='UTEXA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='UUCP' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='VERSION' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='VIRGINIA' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='VOLTAG' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WATER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WED' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WIDGET' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WINDOW' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WIRE' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WONDER' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WORK' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='WORLD' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='XLIB' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='XTERM' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='YEAR' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
if name='YOU' then do;
role = 'REJECTED';
comment = "PRINCOMP2: PRINREJECTED";
end;
