LIBNAME AMUL 'C:\Users\Admin\Documents\GitHub\AMUL-PRACTICA\DATA';

DATA AMUL.RESULTADOS(KEEP=ID_DOCUMENTO CLASE);
  SET AMUL.EM_SAVE_TRAIN;
  IF _SEGMENT_ EQ 8 OR _SEGMENT_ EQ 3 OR _SEGMENT_ EQ 4 OR _SEGMENT_ EQ 1 OR _SEGMENT_ EQ 6 THEN CLASE = "TECNOLOGIA";
  IF _SEGMENT_ EQ 9 OR _SEGMENT_ EQ 7 THEN CLASE = "MEDICINA";
  IF _SEGMENT_ EQ 2 THEN CLASE = "ARMENIA";
  IF _SEGMENT_ EQ 5 OR _SEGMENT_ EQ 10 THEN CLASE = "ISRAELPALESTINA";
RUN;
