LIBNAME AMUL 'C:\Users\Admin\Documents\GitHub\AMUL-PRACTICA\DATA';

/*  TF  */
PROC SQL;
  CREATE TABLE
  WORK.SUM_DOCUMENTO AS
  SELECT ID_DOCUMENTO, PALABRA, NUMVECPAL, SUM(NUMVECPAL) AS OCURRENCIAS
  FROM AMUL.Textmininginputs3
  GROUP BY ID_DOCUMENTO;
QUIT;

DATA TF(DROP = NUMVECPAL);
  SET WORK.SUM_DOCUMENTO;
  TF = NUMVECPAL/OCURRENCIAS;
RUN;

/*  IDF  */

PROC SQL;
  CREATE TABLE
  WORK.COUNT_DOCUMENTO AS
  SELECT ID_DOCUMENTO, PALABRA, NUMVECPAL, COUNT(PALABRA) AS OCURRENCIAS_EN_DOCUMENTO
  FROM AMUL.Textmininginputs3
  GROUP BY PALABRA;
RUN;

DATA IDF(DROP = NUMVECPAL);
  SET WORK.COUNT_DOCUMENTO;
  IDF = LOG(3000/(1+OCURRENCIAS_EN_DOCUMENTO));
RUN;

/*  TFIDF */

PROC SORT DATA = WORK.IDF;
  BY ID_DOCUMENTO PALABRA;
RUN;
QUIT;

PROC SORT DATA = WORK.TF;
  BY ID_DOCUMENTO PALABRA;
RUN;
QUIT;

DATA WORK.MERGED;
  MERGE WORK.IDF WORK.TF;
  BY ID_DOCUMENTO PALABRA;
RUN;

DATA AMUL.VECTORIZADO(KEEP=ID_DOCUMENTO PALABRA TFIDF);
  SET WORK.MERGED;
  TFIDF = TF * IDF;
RUN;

/*  DISTRIBUCIÓN DE SUM(TFIDF) */

PROC SQL;
  CREATE TABLE
  WORK.DISTRIBUCION_TFIDF AS
  SELECT PALABRA, SUM(TFIDF) AS TFIDF_ACUMULADO
  FROM AMUL.VECTORIZADO
  GROUP BY PALABRA;
QUIT;

PROC UNIVARIATE DATA=DISTRIBUCION_TFIDF;
	VAR TFIDF_ACUMULADO;
	OUTPUT OUT=AMUL.PERCENTILES PCTLPTS=(0 to 100 by 0.1) 
	PCTLPRE=PERCENTIL;
RUN;
QUIT;

/* TOMANDO EL PERCENTIL 95 */

DATA WORK.PALABRAS_BUENAS;
SET WORK.DISTRIBUCION_TFIDF;
IF TFIDF_ACUMULADO>=2.1656446965;
RUN;

PROC SQL;
  CREATE TABLE
  WORK.INTERSECCION AS
  SELECT A.ID_DOCUMENTO, A.TFIDF, A.PALABRA
  FROM AMUL.VECTORIZADO A INNER JOIN WORK.PALABRAS_BUENAS B
  ON A.PALABRA = B.PALABRA
  ORDER BY A.ID_DOCUMENTO;
QUIT;

/*  SOLO FALTA TRANSPONER */

PROC SORT DATA = WORK.INTERSECCION OUT = WORK.INTERSECCION_2;
  BY ID_DOCUMENTO PALABRA;
RUN;

PROC TRANSPOSE DATA = WORK.INTERSECCION OUT = WORK.TRANSPUESTO(DROP=_NAME_ _LABEL_);
  VAR TFIDF;
  BY ID_DOCUMENTO;
  ID PALABRA;
RUN;

/* FALTA CAMBIAR LOS DATOS MISSING POR CEROS */

data AMUL.TERMINOS_DOCUMENTOS;
 set WORK.TRANSPUESTO;
 drop _i_;
 array _c_(*) _numeric_;/* Se declara un array compuesto por todas las variables
 numéricas que existen en la tabla (entre ellas, el propio
id_documento) */
 do _i_=2 to dim(_c_);/*La primera variable numérica es el id_documento.Se excluye */
 if _c_(_i_)=. then _c_(_i_)=0;
 end;
 run;
